import type { StateEntry } from './types';

/** Default Indian states & union territories for State Master */
export const defaultStates: StateEntry[] = [
  { slug: 'andhra-pradesh', name: 'Andhra Pradesh', code: 'AP', active: true },
  { slug: 'arunachal-pradesh', name: 'Arunachal Pradesh', code: 'AR', active: true },
  { slug: 'assam', name: 'Assam', code: 'AS', active: true },
  { slug: 'bihar', name: 'Bihar', code: 'BR', active: true },
  { slug: 'chhattisgarh', name: 'Chhattisgarh', code: 'CG', active: true },
  { slug: 'goa', name: 'Goa', code: 'GA', active: true },
  { slug: 'gujarat', name: 'Gujarat', code: 'GJ', active: true },
  { slug: 'haryana', name: 'Haryana', code: 'HR', active: true },
  { slug: 'himachal-pradesh', name: 'Himachal Pradesh', code: 'HP', active: true },
  { slug: 'jharkhand', name: 'Jharkhand', code: 'JH', active: true },
  { slug: 'karnataka', name: 'Karnataka', code: 'KA', active: true },
  { slug: 'kerala', name: 'Kerala', code: 'KL', active: true },
  { slug: 'madhya-pradesh', name: 'Madhya Pradesh', code: 'MP', active: true },
  { slug: 'maharashtra', name: 'Maharashtra', code: 'MH', active: true },
  { slug: 'manipur', name: 'Manipur', code: 'MN', active: true },
  { slug: 'meghalaya', name: 'Meghalaya', code: 'ML', active: true },
  { slug: 'mizoram', name: 'Mizoram', code: 'MZ', active: true },
  { slug: 'nagaland', name: 'Nagaland', code: 'NL', active: true },
  { slug: 'odisha', name: 'Odisha', code: 'OD', active: true },
  { slug: 'punjab', name: 'Punjab', code: 'PB', active: true },
  { slug: 'rajasthan', name: 'Rajasthan', code: 'RJ', active: true },
  { slug: 'sikkim', name: 'Sikkim', code: 'SK', active: true },
  { slug: 'tamil-nadu', name: 'Tamil Nadu', code: 'TN', active: true },
  { slug: 'telangana', name: 'Telangana', code: 'TS', active: true },
  { slug: 'tripura', name: 'Tripura', code: 'TR', active: true },
  { slug: 'uttar-pradesh', name: 'Uttar Pradesh', code: 'UP', active: true },
  { slug: 'uttarakhand', name: 'Uttarakhand', code: 'UK', active: true },
  { slug: 'west-bengal', name: 'West Bengal', code: 'WB', active: true },
  { slug: 'andaman-nicobar', name: 'Andaman and Nicobar Islands', code: 'AN', active: true },
  { slug: 'chandigarh', name: 'Chandigarh', code: 'CH', active: true },
  { slug: 'dadra-nagar-haveli-daman-diu', name: 'Dadra and Nagar Haveli and Daman and Diu', code: 'DH', active: true },
  { slug: 'delhi', name: 'Delhi', code: 'DL', active: true },
  { slug: 'jammu-kashmir', name: 'Jammu and Kashmir', code: 'JK', active: true },
  { slug: 'ladakh', name: 'Ladakh', code: 'LA', active: true },
  { slug: 'lakshadweep', name: 'Lakshadweep', code: 'LD', active: true },
  { slug: 'puducherry', name: 'Puducherry', code: 'PY', active: true },
];
