ALTER TABLE lawyers ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE lawyers ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE lawyers ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT FALSE;
